# nginx proxy address - http://172.17.0.1:60789

name: roundcube
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: roundcube/roundcubemail:latest
    container_name: roundcube-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      ROUNDCUBEMAIL_DB_TYPE: sqlite
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://${EMAIL_SERVER_HOST:-mail.example.com}
      ROUNDCUBEMAIL_SMTP_SERVER: tls://${EMAIL_SERVER_HOST:-mail.example.com}
      ROUNDCUBEMAIL_SMTP_PORT: ${EMAIL_SERVER_PORT:-587}
      ROUNDCUBEMAIL_INSTALL_PLUGINS: "true"
      ROUNDCUBEMAIL_PLUGINS: thunderbird_labels,show_folder_size,tls_icon
      CONTAINER_NAME: roundcube-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:60789:80'
    volumes:
      - './volumes/data/db/sqlite/roundcube:/var/roundcube/db'
      - './volumes/data/roundcube:/var/www/html'
    networks:
      - roundcube
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://roundcube-app:80'
      - 'cloudflare.hostname=roundcube.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.roundcube-app.entrypoints=http'
      - 'traefik.http.routers.roundcube-app-secure.tls=true'
      - 'traefik.http.routers.roundcube-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.roundcube-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.roundcube-app.middlewares=roundcube-app-https-redirect'
      - 'traefik.http.routers.roundcube-app-secure.entrypoints=https'
      - 'traefik.http.routers.roundcube-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.roundcube-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.roundcube-app-secure.service=roundcube-app'
      - 'traefik.http.services.roundcube-app.loadbalancer.server.port=80'

networks:
  roundcube:
    name: roundcube
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
